on:
  push:
  workflow_dispatch:
name: TOC Generator
permissions:
  contents: write
  pull-requests: write
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          FOLDING: true
          TOC_TITLE: Details
          CREATE_PR: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: 'docs: update TOC'
          PR_TITLE: 'docs: update TOC'
          TARGET_PATHS: '*.md'
          BRANCH_NAME: 'docs/update-toc'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'