on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

name: TOC Generator

permissions:
  contents: write
  pull-requests: write

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b docs/update-toc

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOC_TITLE: Details
          FOLDING: true
          CREATE_PR: false
          COMMIT_MESSAGE: 'docs: update TOC'
          TARGET_PATHS: '*.md'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: update TOC'
          title: 'docs: update TOC'
          body: |
            Update Table of Contents.
            Auto-generated by [TOC Generator](https://github.com/technote-space/toc-generator)