on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

name: TOC Generator

permissions:
  contents: write
  pull-requests: write

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create branch and generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOC_TITLE: Details
          FOLDING: true
          CREATE_PR: true
          COMMIT_MESSAGE: 'docs: update TOC'
          TARGET_PATHS: '*.md'
          PR_BRANCH_NAME: 'docs/update-toc'
          PR_TITLE: 'docs: update TOC'
          FORCE_PUSH: true
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NO_PUSH_TO_DEFAULT: true