[tools]
dotnet = '9'
python = '3.10'
ruby = '3.4.2'
go = '1.26.0'
rust = "1.91.1"

[env]
_.python.venv = '{{env.HOME}}/.venv'
_.path = ["/opt/homebrew/opt/libpq/bin"]

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
